### ISSUE TITLE
php7 with memcached and igbinary?

### ISSUE THREAD

**Issue by timsomers** [igbinary/igbinary7#10]
I've been trying to migrate our systems to php7, and the missing piece is igbinary support for memcached. Has anybody gotten this combination to work?

**Comment by TysonAndre** [comment]
Yes, I have
Edit: fixed instructions

First, clone the master branch of the igbinary7 repository: https://github.com/igbinary/igbinary7 (No alpha yet on pecl)

``` bash
phpize
./configure --with-php-config=`which php-config`
make
# make test
sudo make install
cd ..
```

Second, clone php7 branch of memcached https://github.com/php-memcached-dev/php-memcached/tree/php7 (also not yet officially released)

``` bash
phpize
./configure --enable-memcached-igbinary --with-php-config=`which php-config`
make
# Running tests requires the memcached server to be installed locally. See https://github.com/php-memcached-dev/php-memcached/blob/master/.travis/travis.sh
# copy igbinary.so into php-memcached/modules/
# php run-tests.php --show-diff -d extension=modules/memcached.so -d extension=igbinary.so -n ./tests/*.phpt 
sudo make install
```

Third, add the igbinary.so and memcached.so extensions to your php.ini

Make sure that php-config and phpize correspond to php version 7.

Similar instructions for php 5: http://stackoverflow.com/a/14043837
