### ISSUE TITLE
PHP7 version can't unpack data generated by php5 version

### ISSUE THREAD

**Issue by parf** [igbinary/igbinary7#12]
[igbinary-generated-by-php5.igbdata.zip](https://github.com/igbinary/igbinary7/files/328705/igbinary-generated-by-php5.igbdata.zip)
^^ this is not a zip file, this is just saved igbinary file (named as zip to bypass attach filter)

PHP5 can read and write data from/to this file.
PHP7 fails with: igbinary_unserialize_ref: invalid reference

<?php
$r = file_get_contents($argv[1]); 
$d = igbinary_unserialize($r);

seems like problem is in `double` type storage

**Comment by parf** [comment]
i've made a better issue example:

https://gist.github.com/parf/6de34ab52a3573a70abd073ede61a3bc

**Comment by TysonAndre** [comment]
This should be fixed.

For the contents of #13/current master after #13 was merged, the php7 output was:

```
[{"geo":[34.1989453,-118.597305]},{"geo":[37.9429522,-122.3900901]},{"geo":[37.677661,-122.4552162]},{"geo":[29.958529,-90.077003]},{"geo":[47.28,-122.76]},{"geo":[33.9202933,-117.4464354]},{"geo":[37.3,-121.98]},{"geo":[33.7463915,-117.8604472]},{"geo":[33.7513419,-117.9939921]},{"geo":[29.4627365,-95.357994]},{"geo":[29.6185208,-95.6090009]},{"geo":[38.9559442,-76.9455301]},{"geo":[37.6966286,-97.3413212]},{"geo":[37.3,-121.98]},{"geo":[37.3,-121.98]},{"geo":[37.3,-121.98]},{"geo":[42.2717443,-71.7588217]},{"geo":[37.7729273,-122.2143323]},{"geo":[42.8662,-85.8984]},{"geo":[42.3065441,-71.0824613]}]
igbinary_serialize($data) is the same as original-source;
* igbinary_serialize(json_encode(json_decode($original))) is not the same as igbinary_serialize($original);
* igbinary_serialize(unserialize(serialize($original))) is not the same as igbinary_serialize($original);
actual data is exactly the same: igbinary_unserialize(igbinary_serialize(serialize(unserialize($original)))) === $original
```

**Comment by TysonAndre** [comment]
Thanks

If there are any other incompatibilities between php5 and php7 in either direction, please report them
