### ISSUE TITLE
PHP7 PECL release

### ISSUE THREAD

**Issue by TysonAndre** [igbinary/igbinary7#19]
Decide on versioning scheme, and release this to PECL.
## Decide on versioning scheme.

There are three patterns used in other projects I've seen, I prefer the first:
1. Common repository with php5/ folder and php7/ folder, conditionally choosing folder based on php version(E.g. https://pecl.php.net/package/solr).
   Features/functionality in both languages should be equivalent.
   Change travis CI config to combine the more php versions.
   Release as 1.3.0 or 1.3.0-alpha
2. Different major versions (1.2.1 for php5, 2.x for php7). (E.g. https://pecl.php.net/package/apcu)
   (I'd prefer if major versions corresponded to changes to the igbinary serialization format version, instead)
3. A lot of `#ifdef`s. I really don't want to do that since virtually **all** of the code is dealing with implementation details of `zval`s (this is a serializer/unserializer, after all), and it hurts readability.
   Release as 1.3.0 or 1.3.0-alpha
## Release this to PECL

Would need an igbinary maintainer with a pecl account, or for me to obtain a pecl account.

@phadej / @tricky thoughts on versioning?

**Comment by pierrejoye** [comment]
This is what I proposed but was rejected.

I will very happy if the decision is revised.

**Comment by TysonAndre** [comment]
https://github.com/igbinary/igbinary/pull/62 will probably be the pecl release when other maintainers are done with vacation.

**Comment by razvanphp** [comment]
Maybe you can talk with the maintainer of the php7 deb packages to include this in the repo, this would be even better than PECL.

https://packages.sury.org/php/README.txt

CC @oerdnj

**Comment by TysonAndre** [comment]
There's a few more things.

The other maintainers should be finished with their vacation by now, but haven't been active.

https://github.com/igbinary/igbinary - once of the other maintainers wanted to update an error message for the igbinary_unserialize() header. I also plan to merge the changes to enable the igbinary session serializer.

**Comment by TysonAndre** [comment]
This issue (Releasing to PECL) is a duplicate of https://github.com/igbinary/igbinary/issues/86 , which is more recently active.

The 2.0.0 release has already been prepared, and just needs to be pushed to PECL by a maintainer with a PECL account. https://github.com/igbinary/igbinary/releases/tag/2.0.0
